version: '3'

services:
    laravelapp:
        container_name: exapi
        build: .
        ports:
            - "8080:80"
        volumes:
            - ./.docker/nginx/conf.d/default.conf/:/etc/nginx/conf.d/default.conf
            - .:/usr/share/nginx
        environment:
            - APP_URL=https://app.exgate.io
        depends_on:
            - postgres
        networks:
            - networkis
        links:
            - postgres
            
    postgres:
        container_name: exdb
        image: 'postgres'
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "cryptoapi"
            POSTGRES_USER: "crypto_user"
            POSTGRES_PASSWORD: "crypto#1"
        volumes:
            - ./.docker/posgres:/var/lib/postgresql/:rw
        networks:
            - networkis
             
networks: 
    networkis:
        driver: bridge
